# Daily testing workflow
#
# This script is designed to be triggered on the provided cron time,
# and it can be manually triggered. The purposes of this script include:
#
# - running all unit tests against all operators for correctness verification;
# - running all performance tests (benchmarks) against all operators to
#   validate if there are performance regress;
# - running all SVT tests where selected models are launched for E2E tests.
#
# TODO(Qiming): Enable daily tests for benchmark and all backends

name: daily

on:
  workflow_dispatch:

  schedule:
    # Note that the time is in UTC, so we want this to start at 00:03+8:00
    - cron: '3 16 * * *'

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      datetime: ${{ steps.get-date.outputs.CURRENT_DATE }}
    steps:
      - id: get-date
        shell: bash
        run: |
          echo "CURRENT_DATE=$(date +'%Y-%m-%d-%H%M%S')" >> "$GITHUB_OUTPUT"

  cpp-op:
    needs: prepare
    uses: ./.github/workflows/cpp-op-test.yaml

  python-op:
    needs: prepare
    concurrency:
      group: python-op-${{ needs.prepare.outputs.datetime }}
      cancel-in-progress: true
    runs-on: jiuding
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        run: tools/gpu_check.sh
      - shell: bash
        env:
          CHANGED_FILES: '__ALL__'
        run: |
          # Use CURRENT_DATE as a fake PR ID
          bash tools/test-op.sh ${{ needs.prepare.outputs.datetime }}

  examples:
    needs: prepare
    concurrency:
      group: examples-test-${{ needs.prepare.outputs.datetime }}
      cancel-in-progress: true
    runs-on: jiuding
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        run: tools/gpu_check.sh
      - shell: bash
        env:
          CHANGED_FILES: '__ALL__'
        run: |
          bash tools/test-examples.sh ${{ needs.prepare.outputs.datetime }}

#   coverage:
#     needs:
#       - preprocess
#       - blas-op-test
#       - examples-test
#       - quick-cpu-op-test
#       - utils-test
#       - pointwise-op-test
#       - reduction-op-test
#       - special-op-test
#     if: contains(github.event.pull_request.labels.*.name, 'tests')
#     concurrency:
#       group: coverage-test-${{ github.event.pull_request.number || github.ref }}
#       cancel-in-progress: true
#     runs-on: cpu
#     continue-on-error: true
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v6
#       - name: Get python coverage
#         shell: bash
#         run: |
#           git config --global --add safe.directory ../FlagGems
#           if [ "${{ github.event_name }}" == "pull_request" ]; then
#             PR_ID=${{ github.event.pull_request.number }}
#           elif [ "${{ github.event_name }}" == "push" ]; then
#             PR_NUMBER=$(git log -1 --pretty=format:'%s' | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
#             PR_ID=${PR_NUMBER}
#           fi
#           bash tools/code_coverage/coverage.sh ${PR_ID}
#       - name: Report python coverage
#         shell: bash
#         run: |
#           git config --global --add safe.directory ../FlagGems
#           if [ "${{ github.event_name }}" == "pull_request" ]; then
#             PR_ID=${{ github.event.pull_request.number }}
#           elif [ "${{ github.event_name }}" == "push" ]; then
#             PR_NUMBER=$(git log -1 --pretty=format:'%s' | grep -oE '#[0-9]+' | grep -oE '[0-9]+')
#             PR_ID=${PR_NUMBER}
#           fi
#           bash tools/code_coverage/report_coverage.sh ${PR_ID}
