name: op-test

on:
  workflow_call:
    inputs:
      pr_id:
        description: 'The PR ID for generating coverage data'
        type: string
        required: true
      script_path:
        description: 'The path to the operator test script.'
        type: string
        required: true
      changed_files:
        description: 'The files that have been changed, space delimited string list.'
        type: string
        required: false

jobs:
  test:
    runs-on: jiuding
    steps:
      - uses: actions/checkout@v6
      - shell: bash
        run: tools/gpu_check.sh
      - shell: bash
        env:
          CHANGED_FILES: ${{ inputs.changed_files }}
        run: |
          bash tools/${{ inputs.script_path }} ${{ inputs.pr_id }}
