name: Pull Request Stats

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Run Pull Request Stats action
        uses: flowwer-dev/pull-request-stats@v1 # Replace with the correct action version/owner
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
